# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Mijowild
tagline:             'A weblog'
description:         'Pictures and thoughts'
url:                 http://mijowild.com
baseurl:             ''

# About/contact
author:
  name:              Michael Johannes Wild
  url:               https://twitter.com/mijowild
  email:             mijowild@gmail.com

# Custom vars
version:             1.0.0

# it said to include this plugin
gems: [jekyll-paginate]
paginate: 1
paginate_path: "page:num"

